### ISSUE TITLE
Search & Replace

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/php-fpm#16]
Search & Replace is a nice feature, offered by many text editors.
I wan't aware of the fact it's so complicated to use.

https://github.com/stuvusIT/php-fpm/search?utf8=%E2%9C%93&q=php_fpm_pool&type=

Funny how there is a variable used in a template, but never defined anywhere?

**Comment by Scriptkiddi** [comment]
whats your problem? php_fpm_pool is defined 
`loop_control:
    loop_var: php_fpm_pool`

**Comment by dasJ** [comment]
No, this variable is introduced in #22 which isn't merged yet

**Comment by dasJ** [comment]
Sorry, what is this??

![image](https://user-images.githubusercontent.com/4971975/31318114-17b78582-ac4d-11e7-9e0b-11d4ce1e6ad9.png)

**Comment by Scriptkiddi** [comment]
search and replace

**Comment by dasJ** [comment]
http://www.peachpit.com/articles/article.aspx?p=1374386&seqNum=12

**Comment by dasJ** [comment]
http://vimregex.com/

**Comment by Scriptkiddi** [comment]
its fixed in the new pull request
