### ISSUE TITLE
Pools not defined in the host variables should be deleted

### ISSUE THREAD

**Issue by SlothOfAnarchy** [stuvusIT/php-fpm#39]

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 31 days.

**Comment by SlothOfAnarchy** [comment]
This has been resolved [here](https://github.com/stuvusIT/php-fpm/pull/40/files#diff-57d4c90486ef25607ab5b6e3f07e9ce5R66). The pool configs are included directly instead of including the whole directory.
